Cargo.lock, Cargo.toml, README.md, src/args.rs, src/ig/mod.rs, src/ig/search_config.rs, src/main.rs, src/ui/editor.rs
=> Use $EDITOR as a fallback variable

src/ig/mod.rs, src/ui/editor.rs
=> Add support for opening files in VS Code

src/ui/editor.rs
=> add support for emacs and emacsclient

src/args.rs, src/main.rs, src/ui/app.rs, src/ui/mod.rs, src/ui/theme/dark.rs, src/ui/theme/light.rs, src/ui/theme/mod.rs
=> Add theme for light environments

README.md, bucket/igrep.json
=> Scoop package

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs
=> Use ripgrep config file

README.md, src/ui/editor.rs
=> Add support for code-insiders

README.md
Hey! I created the following AUR package for installing `igrep` on Arch Linux:
- https://aur.archlinux.org/packages/igrep
This PR simply updates README.md about installation instructions.
=> Update README.md about AUR package

README.md, src/ui/editor.rs
[Helix](https://helix-editor.com/) is a modal editor inspired by Kakoune.
=> Add support for Helix editor

src/ig/mod.rs, src/ui/app.rs, src/ui/editor.rs, src/ui/theme/mod.rs
fixes #34
Added a new error state in which the editor will display the error message
=> Added error handling for editor failure

README.md, src/ui/editor.rs
["micro - a modern and intuitive terminal-based text 
editor"](https://micro-editor.github.io/)
This resolves #33.
=> add support for the micro editor

README.md, src/ui/editor.rs
I already use it everyday (my own fork), thinking might useful to others as well.
=> Add support of Intellij, Goland and Pycharm

README.md, src/args.rs, src/ig/search_config.rs, src/ig/searcher.rs, src/main.rs
=> Support multiple paths search

README.md, src/ig/mod.rs, src/ig/searcher.rs, src/ui/app.rs, src/ui/input_handler.rs, src/ui/mod.rs, src/ui/search_popup.rs, src/ui/theme/mod.rs
F5 opens search popup.
Resolves #44
=> Allow to change search pattern without closing an app

README.md
Hey 🐻
I packaged `igrep` for Alpine Linux and this PR simply updates README.md to reflect this change.
Thank you!
=> Add instructions for installing on Alpine Linux

README.md, src/ui/app.rs, src/ui/context_viewer.rs, src/ui/input_handler.rs
=> add keybindings for changing context viewer size

README.md, src/ui/editor.rs
Adds the program requested in #53, but doesn't implement the wider suggestion. Also introduces a misnomer into both the code and the README.
=> add less as editor option

README.md, src/args.rs, src/ig/mod.rs, src/main.rs, src/ui/app.rs, src/ui/editor.rs
=> Ability to specify custom command

README.md, src/args.rs, src/ig/search_config.rs, src/ig/searcher.rs, src/main.rs
=> add `follow symlinks` option

Cargo.lock, Cargo.toml, src/editor.rs, src/ig.rs
=> locate editor executable using which crate

src/args.rs, src/ig/search_config.rs, src/ig/searcher.rs, src/main.rs
=> Feature: add `-F` | `--fixed-strings` flag
